giftcardreader: giftcardreader.c
	gcc -o giftcardreader giftcardreaderfixed2.c && ./giftcardreader 1 examplefile.gft


giftcardexamplewriter:
	gcc -o giftcardexamplewriter giftcardexamplewriter.c && ./giftcardexamplewriter


